### ISSUE TITLE
Could there be a cursor based pagination?

### ISSUE THREAD

**Issue by kurexi** [marmelab/timeline-react-admin#1]
In use cases like timeline, the next page depends on the the last item in previous list. And in my particular case there is an extra filed, which indicates the next request parameter, in API response.
I have tried to implement cursor based custom pagination, and ended up with can not passing the extra field to the `<List/>`

API response:
```js
{data:[{}, {}], total: 99, extra:{}}
```

And is there a solution for this kind of pagination?

**Comment by fzaninotto** [comment]
Hi, and thanks for your question. I suggest you ask it on stackOverflow, we don't provide support via Github issues.
